### ISSUE TITLE
Metalsmith 2.4 Roadmap

### ISSUE THREAD

**Issue by webketje** [metalsmith/metalsmith#352]
This issue is meant to group & provide an overview of what features will be in release 2.4. Aiming for december 2021/ January 2022

- [x] Bring dependencies, dev dependencies up-2-date
- [x] #231 - in 2.4 support will be dropped for Node < 8 (EOL=2019). This is necessary for dependency security patches.
- [x] #281 - will reproduce this issue and work out a resolution for this edge-case (A. leave as-is, B. leave for 3.0 due to major breaking change, C. fix in 2.4)
- [x] #338 - 2.4 will add a `metalsmith.match` function for plugins to rely on instead of having to require multiple versions of multimatch/ minimatch. Micromatch is the better option, but important caveat is potential issues on Windows regarding backslashes, see https://github.com/webketje/metalsmith-taxonomy/issues/14
- [x] #211 - will try to provide a better DX for this without breaking backwards compat.
- [x] #223 & #129 - `metalsmith.json`  plugins key object notation will be discouraged starting from 2.4, switching all docs/ examples to use array notation. Add a warning in the CLI. Object property order in JS is not guaranteed. The feature won't be removed, but hidden
- [x] `metalsmith.ignore` should filter out the ignored files *before* they are read into memory, see also #178. TBD if this can be fixed without breaking changes/ changing the entire design.
- [x] Create a PR with updated types for Typescript + inquire about adding plugin types to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/metalsmith
- [x] #226 - provide ability to pass frontmatter options to gray-matter (including a custom engine like `toml`), this is required to keep backwards-compatibility as the new version of gray-matter doesn't include them by default) 
- [x] Use native `fs.rm` instead of `rimraf` when available (Node 14.4+)
- [x] #358
- [x] ~~#355 A) force specifying a `directory` option in `metalsmith.json` (breaking) or B) Make `__dirname` also the default for the JS solution (backwards-compatible)~~ *will not be included in 2.4 as this requires more testing & thought*

**Comment by webketje** [comment]
Unfortunately adding correct JSDoc types for JS modules would clutter the codebase too much and be of no use for typehints such as those VS Code/ Webstorm understand. Until https://github.com/jsdoc/jsdoc/issues/1645 is resolved a better approach is to include JSDocs those editors do understand, and create a separate JS file with comments only to generate a JSDoc API page on the metalsmith.io repository
