### ISSUE TITLE
Metalsmith 2.6 Roadmap

### ISSUE THREAD

**Issue by webketje** [metalsmith/metalsmith#386]
- [x] CLI: new build options `--env` and `--debug` with higher precedence than a config's
- [x] CLI: new build option `--dry-run` (mapping to Metalsmith#process)
- [x] CLI: support JS configs (CJS-only for the moment) 
- [x] Fix a duplicate empty input check in metalsmith.match cf 60e173a090486b9a06064f1310491f1ed9e40274
- [ ] Include experimental `watch` method, cf #379
- [ ] Include TS support in main repo, implies merging `@types/metalsmith`, cf #356 
- [ ] Update README.md
- [ ] Expose `metalsmith#matter` member object with `parse` and `stringify` utility methods

**Comment by exortech** [comment]
Cool to see that support for watching has been added. Thanks @webketje for that.

What is everyone doing for local site testing? I had been using [metalsmith-serve](https://github.com/mayo/metalsmith-serve) but it's now officially archived and had been dependent on node-static which has unresolved security issues. This feels like another thing that should be easy to do with Metalsmith and that there should be a built-in (or at least officially sanctioned) way to do this. FWIW, 11ty does with https://github.com/11ty/eleventy-dev-server. Curious what others are doing here. Adding it to this issue as it could merit inclusion somewhere on the roadmap.

**Comment by webketje** [comment]
@exortech I added a section to the docs a while ago about [auto-rebuild and browser live-reload](https://metalsmith.io/docs/usage-guide/#auto-rebuild-and-browser-live-reload)


I posted a signature snippet in the Gitter channel with the signature of the future watch feature (it collects config from clean() and watch() methods and can be used with process() too):

```js
Metalsmith(__dirname)
  // watches metalsmith.source() by default
  .watch(true)
  // watch custom dirs, override chokidar options
  .watch(['layouts', 'src'], { interval: 2000 })
  // clean: true for full rebuild, false for partial
  .clean(false)
  // output files...
  .build(funtion onEachRebuild(err, files) {
    // if clean:false, files will only be the changed files!
    console.log('Rebuild finished!')
  })
  // or only do a 'dry-run' (no writes)
  .process(funtion onEachReprocess(err, files) {
    // if clean:false, files will only be the changed files!
    console.log('Reprocessed!')
  })
```

Below is a snippet of my local tests using browser-sync as dev-server in combination with the 2.6 watcher, it's quite straight-forward:

```js
const bs = require('browser-sync')
const devserver = bs.create('devserver')
devserver.init({ server: 'build', open: false, port: 3000, watch: false, injectChanges: false })
 
metalsmith
   .clean(true)
   .watch(['lib','src'])
   .env('DEBUG', process.env.DEBUG)
   .build(err => {
       if (err) {
          console.log(err)
          throw err;
       }
       console.log(`Build success in ${((performance.now() - t1) / 1000).toFixed(1)}s`);
       devserver.reload()
     });
 }
```

**Comment by exortech** [comment]
Thanks @webketje. Much appreciated. I'll give it a try.
