### ISSUE TITLE
Metalsmith 2.7 roadmap

### ISSUE THREAD

**Issue by webketje** [metalsmith/metalsmith#405]
Branch: [release/2.7.0](https://github.com/metalsmith/metalsmith/commits/release/2.7.0/)

- [ ] <s>#404</s> (moved to next release)
- [x] Add `Metalsmith.version` static property 7a2f38b
- [x] #397 
- [x] #403 (tracked in branch [feat/#403-imports-method](https://github.com/metalsmith/metalsmith/commits/feature/%23403-imports-method/?since=2024-03-05))
- [ ] <s>#392</s> (moved to next release)
- [x] #409
- [x] #361 
- [x] #380

**Comment by webketje** [comment]
@AndreKelling You are fast :) , you can already test it out by doing `npm i github:metalsmith/metalsmith`, but I still need to publish the news/API/CLI docs on metalsmith.io. Here you can already read about the 2 new methods (imports & statik): https://github.com/metalsmith/metalsmith.io/blob/release/2.7.0/src/api.md
